---
resources:
- name: resource-TDD-Training-Application
  type: git
  source:
    uri: https://github.com/codecentric/TDDTrainingApplication.git
    branch: concourse-solution
- name: docker-image
  type: docker-image
  source:
    repository: concourse/docker-image


jobs:
- name: job-build-application
  serial: true
  plan:
  - get: resource-TDD-Training-Application
  - task: unit
    file: resource-TDD-Training-Application/TDDTrainingApplicationCC/ci/task_build.yml

- name: job-integrationtest-application
  plan:
  - get: resource-TDD-Training-Application
    passed: [job-build-application]
    trigger: true
  - task: unit
    file: resource-TDD-Training-Application/TDDTrainingApplicationCC/ci/task_integrationtests.yml

- name: job-docker-build
  plan:
  - get: resource-TDD-Training-Application
    passed: [job-integrationtest-application]
    trigger: true
  - put: docker-image
    params:
      build: resource-TDD-Training-Application/TDDTrainingApplicationCC/docker

