---
resources:
- name: resource-TDD-Training-Application
  type: git
  source:
    uri: https://github.com/codecentric/TDDTrainingApplication.git
    branch: concourse-solution

jobs:
- name: job-build-application
  serial: true
  plan:
  - get: resource-TDD-Training-Application
  - task: unit
    file: resource-TDD-Training-Application/TDDTrainingApplicationCC/ci/task_build.yml

- name: job-integrationtest-application
  plan:
  - get: resource-TDD-Training-Application
    passed: [job-build-application]
    trigger: true
  - task: permissions
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: khozzy/selenium-java-firefox, tag: "latest"}
      inputs:
      - name: resource-TDD-Training-Application
      run:
        path: ./resource-TDD-Training-Application/TDDTrainingApplicationCC/ci/update_permissions.sh
  - task: unit
    file: resource-TDD-Training-Application/TDDTrainingApplicationCC/ci/task_integrationtests.yml
